/*
真正的C++语言，全是c和C
*/
#ifndef REAL_CPP_LANG_H
#define REAL_CPP_LANG_H
// 内置类
#define CCCCCCCC int
#define CCCCCCCc float
#define CCCCCCcC double
#define CCCCCcCC long
#define CCCCcCCC long long
#define CCCcCCCC long double
#define CCcCCCCC char
#define CcCCCCCC const
#define cCCCCCCC auto
#define CCCCCCcc bool
#define CCCCCccC short
#define CCCCccCC signed
#define CCCccCCC unsigned
#define CCccCCCC volatile
#define CccCCCCC mutable
#define ccCCCCCC static
#define CCCCCccc extern
#define CCCCcccC wchar_t
#define CCCcccCC char8_t
#define CCcccCCC char16_t
#define CcccCCCC char32_t
// standard中的东西
#define CCCCCcCCC std::string
#define CCCCcCCCC std::stack
#define CCCcCCCCC std::queue
#define CCcCCCCCC std::vector
#define CcCCCCCCC std::deque
#define cCCCCCCCC std::list
#define CCCCCCCcc std::forward_list
#define CCCCCCccC std::array
#define CCCCCccCC std::basic_string
#define CCCCccCCC std::set
#define CCCccCCCC std::multiset
#define CCccCCCCC std::map
#define CccCCCCCC std::multimap
#define ccCCCCCCC std::unordered_set
#define CCCCCCccc std::unordered_multiset
#define CCCCCcccC std::unordered_map
#define CCCCcccCC std::unordered_multimap
#define CCCcccCCC std::priority_queue
#define CCcccCCCC std::unique_ptr
#define CcccCCCCC std::shared_ptr
#define cccCCCCCC std::weak_ptr
#define CCCCCcccc std::pair
#define CCCCccccC std::tuple
#define CCCccccCC std::optional
#define CCccccCCC std::variant
#define CccccCCCC std::any
#define ccccCCCCC std::function
#define CCCCccccc std::wstring
#define CCCcccccC std::u8string
#define CCcccccCC std::u16string
#define CcccccCCC std::u32string
#define cccccCCCC std::istream
#define CCCcccccc std::ostream
#define CCccccccC std::iostream
#define CccccccCC std::ifstream
#define ccccccCCC std::ofstream
#define CCccccccc std::fstream
#define CcccccccC std::stringstream
#define cccccccCC std::istringstream
#define Ccccccccc std::ostringstream
#define ccccccccC std::exception
#define ccccccccc std::runtime_error
#define CCCCCCCCCC std::logic_error
#define CCCCCCCCCc std::invalid_argument
#define CCCCCCCCcC std::domain_error
#define CCCCCCCcCC std::length_error
#define CCCCCCcCCC std::out_of_range
#define CCCCCcCCCC std::future_error
#define CCCCcCCCCC std::range_error
#define CCCcCCCCCC std::overflow_error
#define CCcCCCCCCC std::underflow_error
#define CcCCCCCCCC std::system_error
#define cCCCCCCCCC std::regex_error
#define CCCCCCCCcc std::bad_alloc
#define CCCCCCCccC std::bad_cast
#define CCCCCCccCC std::bad_typeid
#define CCCCCccCCC std::bad_optional_access
#define CCCCccCCCC std::bad_variant_access
#define CCCccCCCCC std::bad_weak_ptr
#define CCccCCCCCC std::bad_function_call
#define CccCCCCCCC std::ios_base::failure
#define ccCCCCCCCC std::complex
#define CCCCCCCccc std::valarray
#define CCCCCCcccC std::bitset
#define CCCCCcccCC std::chrono::duration
#define CCCCcccCCC std::chrono::time_point
#define CCCcccCCCC std::chrono::day
#define CCcccCCCCC std::chrono::month
#define CcccCCCCCC std::chrono::year
#define cccCCCCCCC std::initializer_list
#define CCCCCCcccc std::type_index
#define CCCCCccccC std::type_info
#define CCCCccccCC std::nullptr_t
#define CCCccccCCC std::byte
#define CCccccCCCC std::span
#define CccccCCCCC std::string_view
#define ccccCCCCCC std::ranges_view
#define CCCCCccccc std::type_identity
#define CCCCcccccC std::type_list
#define CCCcccccCC std::is_integral
#define CCcccccCCC std::reference_wrapper
#define CcccccCCCC std::bind
#define cccccCCCCC std::is_floating_point
#define CCCCcccccc std::is_pointer
#define CCCccccccC std::integer_sequence
#define CCccccccCC std::index_sequence
#define CccccccCCC std::basic_ios
#define ccccccCCCC std::basic_streambuf
#define CCCccccccc std::basic_ostream
#define CCcccccccC std::basic_iostream
#define CcccccccCC std::error_code
#define cccccccCCC std::error_category
#define CCcccccccc std::error_condition
#define CccccccccC std::system_error
#define ccccccccCC std::expected
#define Cccccccccc std::thread
#define cccccccccC std::jthread
#define cccccccccc std::mutex
#define CCCCCCC std::recursive_mutex
#define CCCCCCc std::timed_mutex
#define CCCCCcC std::shared_mutex
#define CCCCcCC std::lock_guard
#define CCCcCCC std::unique_lock
#define CCcCCCC std::shared_lock
#define CcCCCCC std::scoped_lock
#define cCCCCCC std::atomic
#define CCCCCcc std::atomic_flag
#define CCCCccC std::atomic_ref
#define CCCccCC std::promise
#define CCccCCC std::future
#define CccCCCC std::shared_future
#define ccCCCCC std::packaged_task
#define CCCCccc std::condition_variable
#define CCCcccC std::condition_variable_any
#define CCcccCC std::complex
#define CcccCCC std::valarray
#define cccCCCC std::bitset
#define CCCcccc std::random_device
#define CCccccC std::mt19937
#define CccccCC std::uniform_int_distribution
#define ccccCCC std::numeric_limits
#define CCccccc std::ratio
#define CcccccC std::numbers::pi
#define cccccCC std::numbers::e
#define Ccccccc std::filesystem::path
#define ccccccC std::filesystem::directory_entry
#define ccccccc std::filesystem::directory_iterator
#define CCCCCC std::filesystem::recursive_dirctory_iterator
#define CCCCCc std::filesystem::file_status
#define CCCCcC std::filesystem::space_info
#define CCCcCC std::basic_regex
#define CCcCCC std::sub_match
#define CcCCCC std::cout
#define cCCCCC std::cin
#define CCCCcc std::endl
#define CCCccC std::time
#define CCccCC std::srand
#define CccCCC std::rand
#define ccCCCC std::match_results
#define CCCccc std::regex_iterator
#define CCcccC std::regex_token_iterator
#define CcccCC std::format_context
#define cccCCC std::basic_format_arg
#define CCcccc std::format_args
#define CccccC std::format_error
#define ccccCC std::coroutine_handle
#define Cccccc std::coroutine_traits
#define cccccC std::suspend_always
#define cccccc std::suspend_never
#define CCCCCCCCCCC std::monostate
#define CCCCCCCCCCc std::strong_ordering
#define CCCCCCCCCcC std::weak_ordering
#define CCCCCCCCcCC std::partial_ordering
#define CCCCCCCcCCC std::common_reference
#define CCCCCCcCCCC std::common_type
#define CCCCCcCCCCC std::less
#define CCCCcCCCCCC std::greater
#define CCCcCCCCCCC std::equal_to
#define CCcCCCCCCCC std::allocator_arg_t
#define CcCCCCCCCCC std::piecewise_construct_t
#define cCCCCCCCCCC namespace
#define CCCCCCCCCcc struct
#define CCCCCCCCccC std::in_place_t
#define CCCCCCCccCC std::chrono::steady_clock
// 关键字
#define CCCCCCccCCC class
#define CCCCCccCCCC protected
#define CCCCccCCCCC public
#define CCCccCCCCCC private
#define CCccCCCCCCC void
#define CccCCCCCCCC if
#define ccCCCCCCCCC else
#define CCCCCCCCccc switch
#define CCCCCCCcccC case
#define CCCCCCcccCC default
#define CCCCCcccCCC for
#define CCCCcccCCCC while
#define CCCcccCCCCC do
#define CCcccCCCCCC break
#define CcccCCCCCCC continue
#define cccCCCCCCCC goto
#define CCCCCCCcccc return
#define CCCCCCccccC inline
#define CCCCCccccCC virtual
#define CCCCccccCCC override
#define CCCccccCCCC final
#define CCccccCCCCC explicit
#define CccccCCCCCC constexpr
#define ccccCCCCCCC consteval
#define CCCCCCccccc constinit
#define CCCCCcccccC union
#define CCCCcccccCC enum
#define CCCcccccCCC enum class
#define CCcccccCCCC friend
#define CcccccCCCCC this
#define cccccCCCCCC operator
#define CCCCCcccccc sizeof
#define CCCCccccccC alignof
#define CCCccccccCC alignas
#define CCccccccCCC template
#define CccccccCCCC typename
#define ccccccCCCCC requires
#define CCCCccccccc concept
#define CCCcccccccC using
#define CCcccccccCC asm
#define CcccccccCCC try
#define cccccccCCCC catch
#define CCCcccccccc throw
#define CCccccccccC noexcept
#define CccccccccCC static
#define ccccccccCCC thread_local
#define CCccccccccc register
#define CcccccccccC restrict
#define cccccccccCC dynamic_cast
#define CCCCCCCCcCc static_cast
#define cCCccCCCCCC const_cast
#define ccccccccccc reinterpret_cast
#define CCCCC typedef
#define CCCCc decltype
#define CCCcC typeid
#define CCcCC new
#define CcCCC delete
#define cCCCC co_await
#define CCCcc co_yield
#define CCccC co_return
// 头文件名
#define CccCC <cstddef>
#define ccCCC <cstdint>
#define CCccc <climits>
#define CcccC <cfloat>
#define cccCC <cstdalign>
#define Ccccc <cstdarg>
#define ccccC <cstdbool>
#define ccccc <csetjmp>
#define CCCCCCCCCCCC <csignal>
#define CCCCCCCCCCCc <ctime>
#define CCCCCCCCCCcC <cassert>
#define CCCCCCCCCcCC <new>
#define CCCCCCCCcCCC <memory>
#define CCCCCCCcCCCC <typeinfo>
#define CCCCCCcCCCCC <typeindex>
#define CCCCCcCCCCCC <type_traits>
#define CCCCcCCCCCCC <limits>
#define CCCcCCCCCCCC <exception>
#define CCcCCCCCCCCC <stdexcept>
#define CcCCCCCCCCCC <system_error>
#define cCCCCCCCCCCC <string>
#define CCCCCCCCCCcc <cstring>
#define CCCCCCCCCccC <cwchar>
#define CCCCCCCCccCC <cuchar>
#define CCCCCCCccCCC <regex>
#define CCCCCCccCCCC <array>
#define CCCCCccCCCCC <vector>
#define CCCCccCCCCCC <deque>
#define CCCccCCCCCCC <forward_list>
#define CCccCCCCCCCC <list>
#define CccCCCCCCCCC <set>
#define ccCCCCCCCCCC <map>
#define CCCCCCCCCccc <unordered_set>
#define CCCCCCCCcccC <unordered_map>
#define CCCCCCCcccCC <stack>
#define CCCCCCcccCCC <queue>
#define CCCCCcccCCCC <bitset>
#define CCCCcccCCCCC <iterator>
#define CCCcccCCCCCC <algorithm>
#define CCcccCCCCCCC <numeric>
#define CcccCCCCCCCC <cmath>
#define cccCCCCCCCCC <complex>
#define CCCCCCCCcccc <valarray>
#define CCCCCCCccccC <random>
#define CCCCCCccccCC <ratio>
#define CCCCCccccCCC <cfenv>
#define CCCCccccCCCC <ios>
#define CCCccccCCCCC <iosfwd>
#define CCccccCCCCCC <iostream>
#define CccccCCCCCCC <istream>
#define ccccCCCCCCCC <ostream>
#define CCCCCCCccccc <iomanip>
#define CCCCCCcccccC <sstream>
#define CCCCCcccccCC <streambuf>
#define CCCCcccccCCC <cstdio>
#define CCCcccccCCCC <cwchar>
#define CCcccccCCCCC <fstream>
#define CcccccCCCCCC <syncstream>
#define cccccCCCCCCC <locale>
#define CCCCCCcccccc <clocale>
#define CCCCCccccccC <codecvt>
#define CCCCccccccCC <thread>
#define CCCccccccCCC <mutex>
#define CCccccccCCCC <shared_mutex>
#define CccccccCCCCC <future>
#define ccccccCCCCCC <condition_variable>
#define CCCCCccccccc <atomic>
#define CCCCcccccccC <filesystem>
#define CCCcccccccCC <coroutine>
#define CCcccccccCCC <ranges>
#define CcccccccCCCC <format>
#define cccccccCCCCC <utility>
#define CCCCcccccccc <functional>
#define CCCccccccccC <tuple>
#define CCccccccccCC <optional>
#define CccccccccCCC <variant>
#define ccccccccCCCC <any>
#define CCCccccccccc <initializer_list>
#define CCcccccccccC <bit>
#define CcccccccccCC <compare>
#define cccccccccCCC <concepts>
#define CCcccccccccc <numbers>
#define CccccccccccC <span>
#define ccccccccccCC <stop_token>
#define Cccccccccccc <source_location>
#define cccccccccccC <version>
#define cccccccccccc <ciso646>
#define CCccccCCccCC <cstdlib>
//C标准库函数
#define CCCCCCCCcCcC printf
#define CCCcCCCccccC scanf
#define CcccccCCCCcC fprintf
#define CccccCCCcCCC fscanf
#define cCCCccCCCcCC sprintf
#define CCccccCCCccCc sscanf
#define CccCCcCcCcCcC fopen
#define ccCccCCccCCCC fclose
#define CcccCCCCcCCcc fread
#define ccCCcccCCCccC fwrite
#define ccccCCcCCcCCc fseek
#define CCCCccCcCCcCC ftell
#define CcccCCcCCcCCc feof
#define CccCCCcccCccC ferror
#define ccCCccCCccCCC strlen
#define CcCCCCccccCCc strcpy
#define ccccCCccCCCCC strncpy
#define cccccccCCCCCc strcat
#define CCcccCCcCccCC strncat
#define CccccccccCCCc strcmp
#define cCcccccccccCC strncmp
#define cCCCCCCcccCCc strchr
#define CCCCCCCCCCCCC strrchr
#define CCCCCCCCCCCCc strstr
#define CCCCCCCCCCCcC memcpy
#define CCCCCCCCCCcCC memmove
#define CCCCCCCCCcCCC memset
#define CCCCCCCCcCCCC memcmp
#define CCCCCCCcCCCCC sin
#define CCCCCCcCCCCCC cos
#define CCCCCcCCCCCCC tan
#define CCCCcCCCCCCCC asin
#define CCCcCCCCCCCCC acos
#define CCcCCCCCCCCCC atan
#define CcCCCCCCCCCCC atan2
#define cCCCCCCCCCCCC sinh
#define CCCCCCCCCCCcc cosh
#define CCCCCCCCCCccC tanh
#define CCCCCCCCCccCC exp
#define CCCCCCCCccCCC log
#define CCCCCCCccCCCC log10
#define CCCCCCccCCCCC sqrt
#define CCCCCccCCCCCC pow
#define CCCCccCCCCCCC fabs
#define CCCccCCCCCCCC ceil
#define CCccCCCCCCCCC floor
#define CccCCCCCCCCCC fmod
#define ccCCCCCCCCCCC abs
#define CCCCCCCCCCccc isalpha
#define CCCCCCCCCcccC isdigit
#define CCCCCCCCcccCC isalnum
#define CCCCCCCcccCCC isspace
#define CCCCCCcccCCCC islower
#define CCCCCcccCCCCC isupper
#define CCCCcccCCCCCC tolower
#define CCCcccCCCCCCC toupper
#define CCcccCCCCCCCC malloc
#define CcccCCCCCCCCC calloc
#define cccCCCCCCCCCC realloc
#define CCCCCCCCCcccc free
//C++标准库函数/流操作符（cout、cin、endl被我搬到standard了）
#define CCCCCCCCccccC std::cerr
#define CCCCCCCccccCC std::clog
#define CCCCCCccccCCC std::operator
#define CCCCccccCCCCC std::flush
#define CCCccccCCCCCC std::setw
#define CCccccCCCCCCC std::setprecision
#define CccccCCCCCCCC std::fixed
#define ccccCCCCCCCCC std::scientific
#define CCCCCCCCccccc std::hex
#define CCCCCCCcccccC std::dec
#define CCCCCCcccccCC std::oct
#define CCCCCcccccCCC std::string::string
#define CCCCcccccCCCC std::string::size
#define CCCcccccCCCCC std::string::length
#define CCcccccCCCCCC std::string::capacity
#define CcccccCCCCCCC std::string::empty
#define cccccCCCCCCCC std::string::operator
#define CCCCCCCcCcccc std::string::at //这一行开始，我知道怎么排序更多了
#define CCCCCCcCCcccc std::string::front
#define CCCCCcCCCcccc std::string::back
#define CCCCcCCCCcccc std::string::append
#define CCCcCCCCCcccc std::string::insert
#define CCcCCCCCCcccc std::string::erase
#define CcCCCCCCCcccc std::string::replace
#define cCCCCCCCCcccc std::string::clear
#define CCCCCCCccCccc std::string::find
#define CCCCCCccCCccc std::string::rfind
#define CCCCCccCCCccc std::string::find_first_of
#define CCCCccCCCCccc std::string::find_last_of
#define CCCccCCCCCccc std::string::substr
#define CCccCCCCCCccc std::string::compare
#define CccCCCCCCCccc begin
#define ccCCCCCCCCccc end
#define CCCCCCCcccCcc rbegin
#define CCCCCCcccCCcc rend
#define CCCCCcccCCCcc size
#define CCCCcccCCCCcc empty
#define CCCcccCCCCCcc resize
#define CCcccCCCCCCcc operator[]
#define CcccCCCCCCCcc at
#define cccCCCCCCCCcc front
#define CCCCCCCccccCc back
#define CCCCCCccccCCc push_back
#define CCCCCccccCCCc pop_back
#define CCCCccccCCCCc insert
#define CCCccccCCCCCc erase
#define CCccccCCCCCCc clear
#define CccccCCCCCCCc std::sort
#define ccccCCCCCCCCc std::find
#define CCCCCCCcccccc std::binary_search
#define CCCCCCccccccC std::count
#define CCCCCccccccCC std::for_each
#define CCCCccccccCCC std::transform
#define CCCccccccCCCC std::copy
#define CCccccccCCCCC std::fill
#define CccccccCCCCCC std::reverse
#define ccccccCCCCCCC std::max
#define CCCCCCcCccccc std::min
#define CCCCCcCCccccc std::swap
#define CCCCcCCCccccc std::make_unique
#define CCCcCCCCccccc std::make_shared
#define CCcCCCCCccccc std::make_unique_for_overwrite
#define CcCCCCCCccccc std::move
#define cCCCCCCCccccc std::forward
#define CCCCCCccCcccc std::swap
#define CCCCCccCCcccc std::pair
#define CCCCccCCCcccc std::makepair
#define CCCccCCCCcccc std::get
#define CCccCCCCCcccc std::tie
#define CccCCCCCCcccc std::bind
#define ccCCCCCCCcccc std::operator()
#define CCCCCCcccCccc std::ref
#define CCCCCcccCCccc std::cref
#define CCCCcccCCCccc std::accumulate
#define CCCcccCCCCccc std::inner_product
#define CCcccCCCCCccc std::partial_sum
#define CcccCCCCCCccc std::iota
#define cccCCCCCCCccc std::mt19937::operator
#define CCCCCCccccCcc std::uniform_int_distribution<int>::operator()
#define CCCCCccccCCcc std::normal_distribution<double>::operator()
#define CCCCccccCCCcc std::thread::thread
#define CCCccccCCCCcc std::thread::join
#define CCccccCCCCCcc std::thread::detach
#define CccccCCCCCCcc std::mutex::lock
#define ccccCCCCCCCcc std::mutex::unlock
#define CCCCCCcccccCc std::lock_guard
#define CCCCCcccccCCc lock_guard
#define CCCCcccccCCCc std::async
#define CCCcccccCCCCc std::system_clock::now
#define CCcccccCCCCCc std::chrono::duration_cast
//C++库中的宏
#define CcccccCCCCCCc __cplusplus
#define cccccCCCCCCCc __DATE__
#define CCCCCCccccccc __TIME__
#define CCCCCcccccccC __TIMESTAMP__
#define CCCCcccccccCC __FILE__
#define CCCcccccccCCC __LINE__
#define CCcccccccCCCC __func__
#define CcccccccCCCCC __FUNCTION__
#define cccccccCCCCCC __PRETTY_FUNCTION__
#define CCCCCcCcccccc __STDC__
#define CCCCcCCcccccc __STDC_VERSION__
#define CCCcCCCcccccc __STDC_HOSTED__
#define CCcCCCCcccccc __has_include
#define CcCCCCCcccccc __cpp_exceptions
#define cCCCCCCcccccc __cpp_rtti
#define CCCCCccCccccc __cpp_constexpr
#define CCCCccCCccccc __cpp_variadic_templates
#define CCCccCCCccccc __cpp_lambdas
#define CCccCCCCccccc __cpp_range_based_for
#define CccCCCCCccccc __cpp_initializer_lists
#define ccCCCCCCccccc __cpp_generic_lambdas
#define CCCCCcccCcccc __cpp_if_constexpr
#define CCCCcccCCcccc __cpp_concepts
#define CCCcccCCCcccc __cpp_modules
#define CCcccCCCCcccc __cpp_coroutines
#define CcccCCCCCcccc __x86_64__
#define cccCCCCCCcccc __i386__
#define CCCCCccccCccc __arm__
#define CCCCccccCCccc __aarch64__
#define CCCccccCCCccc __LP64__
#define CCccccCCCCccc _WIN32
#define CccccCCCCCccc _WIN64
#define ccccCCCCCCccc INT_MAX
#define CCCCCcccccCcc INT_MIN
#define CCCCcccccCCcc LONG_MAX
#define CCCcccccCCCcc LONG_MIN
#define CCcccccCCCCcc LLONG_MAX
#define CcccccCCCCCcc LLONG_MIN
#define cccccCCCCCCcc CHAR_BIT
#define CCCCCccccccCc SCHAR_MAX
#define CCCCccccccCCc SCHAR_MIN
#define CCCccccccCCCc UCHAR_MAX
#define CCccccccCCCCc FLT_MAX
#define CccccccCCCCCc FLT_MIN
#define ccccccCCCCCCc DBL_MAX
#define CCCCcCcccccCc DBL_MIN
#define CCCcCCcccccCc HUGE_VAL
#define CCcCCCcccccCc INFINITY
#define CcCCCCcccccCc NAN
//main函数
#define cCCCCCcccccCc int main()
// 特定值
#define CCCCccCccccCc true
#define CCCccCCccccCc false
#define CCccCCCccccCc nullptr
#define CccCCCCccccCc NULL
// 特殊：执行命令system("chcp 65001 > nul")
#define cCCCCccCCCCcC system("chcp 65001 > nul")
#endif